name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Five
      id: five
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Five
        setup-command: pip install nbformat
        command: python ./grade_quiz.py
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        FIVE_RESULTS: "${{steps.five.outputs.result}}"
      with:
        runners: five